import "./globals.css";
import type { Metadata } from "next";

import { primaryFont, secondaryFont } from "../settings/fonts";

export const metadata: Metadata = {
    title: "Create Turborepo",
    description: "Generated by create turbo",
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
    return (
        <html lang="en">
            <body className={`${primaryFont.variable} ${secondaryFont.variable} font-sans`}>
                {children}
            </body>
        </html>
    );
}
